### ISSUE TITLE
Error: Cannot find module './_assignValue'

### ISSUE THREAD

**Issue by krishnakumarcitrus** [parse-community/parse-dashboard#345] opened 2016-05-13 08:22 UTC
Error when running 

`npm run dashboard`

Latest parse-dashboard is used. The debug log is:
Do you know what might have went wrong?

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dashboard' ]
2 info using npm@2.15.1
3 info using node@v4.4.4
4 verbose run-script [ 'predashboard', 'dashboard', 'postdashboard' ]
5 info predashboard parse-dashboard@1.0.11
6 info dashboard parse-dashboard@1.0.11
7 verbose unsafe-perm in lifecycle true
8 info parse-dashboard@1.0.11 Failed to exec dashboard script
9 verbose stack Error: parse-dashboard@1.0.11 dashboard: `node ./Parse-Dashboard/index.js & webpack --config webpack/build.config.js --progress --watch`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid parse-dashboard@1.0.11
11 verbose cwd /home/ec2-user/parse/parse-dashboard/Parse-Dashboard
12 error Linux 4.4.5-15.26.amzn1.x86_64
13 error argv "/usr/bin/node" "/usr/bin/npm" "run" "dashboard"
14 error node v4.4.4
15 error npm  v2.15.1
16 error code ELIFECYCLE
17 error parse-dashboard@1.0.11 dashboard: `node ./Parse-Dashboard/index.js & webpack --config webpack/build.config.js --progress --watch`
17 error Exit status 1
18 error Failed at the parse-dashboard@1.0.11 dashboard script 'node ./Parse-Dashboard/index.js & webpack --config webpack/build.config.js --progress --watch'.
18 error This is most likely a problem with the parse-dashboard package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ./Parse-Dashboard/index.js & webpack --config webpack/build.config.js --progress --watch
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs parse-dashboard
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls parse-dashboard
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by krishnakumarcitrus** [comment] 2016-05-13 16:03
Node version is 4.44 is used.
Dashboard page loads, but `Uncaught SyntaxError: Unexpected token < dashboard.bundle.js`

**Comment by drew-gross** [comment] 2016-06-01 00:58
Sorry for the late response. If you haven't yet, I suggest getting the dashboard from `npm install`. Let me know if you have issues with that.

**Comment by nderkach** [comment] 2016-10-24 20:18
Same issue here, is there a solution for it yet?

**Comment by flovilmart** [comment] 2016-10-24 20:21
Did you install the dashboard from git or from NPM? You should install from NPM.

**Comment by nderkach** [comment] 2016-10-24 20:33
it works when installing from npm, whereas I get the error above when cloning the repository. Is that by design?

**Comment by flovilmart** [comment] 2016-10-24 20:35
it's because the dashboard gets built using web pack and the built elements are not committed to the repository.

**Closed** 2018-06-26 18:20 UTC
