### ISSUE TITLE
Filters is missing "objectId" in 2.0.3

### ISSUE THREAD

**Issue by omairvaiyani** [parse-community/parse-dashboard#1297] opened 2019-09-18 14:52 UTC
Hey, loving the changes in `v2`, very happy to see new work happening on this repo! Just a bug I've noticed in `2.0.3`, the filters dropdown is missing `"objectId"`. This also happens to be the filter we use most often when searching for a specific record - if others agree, is it also worth having a quick input field, perhaps next to the Class title, which expands an input box and let's us `quick find` a record by `"objectId"`?

**Comment by W0lfw00d** [comment] 2019-09-30 10:00
It seems to have been becaused by this pull request: #1283

**Comment by j4zz** [comment] 2019-10-01 13:03
We’d like to see a quick fix for this. It’s one of the most used filters for us.

**Closed** 2019-10-02 05:49 UTC
Labels: needs investigation

**Comment by Aud123** [comment] 2019-10-17 08:34
Hi. 
I see the issue has been closed but as I am still running version 2.0.3 of the parse-dashboard, and to this day, the objectId is still missing from the filter. It is true to say that the objectId filter comes really handy. What's the update on that? Or can you re-direct me to a discussion that explains how to solve this? Thanks a lot!
