### ISSUE TITLE
Dashboard error : form tampered with

### ISSUE THREAD

**Issue by trondkr** [parse-community/parse-dashboard#878] opened 2018-08-16 10:53 UTC
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x ] You're running version >=1.0.23 of Parse Dashboard.

- [x] You're running version >=2.3.2 of Parse Server.

- [x ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
I am running Parse server 2.8.4 with Parse Dashboard 1.2.0 on AWS EBS. My Parse-server works fine but I am unable to login to my dashboard and I get the error "form tampered with".  If I revert to version 1.1.0 it all works well.

From what I could gather online it could be an issue with missing cookie-secret but I thought I solved that by adding the following:

`useEncryptedPasswords: true,
    allowInsecureHTTP: false,
    trustProxy: 1,
    cookieSessionSecret: process.env.COOKIE_SECRET
`

Is there something else I am missing here or is this a bug? Thanks for your help. Cheers, Trond

**Comment by flovilmart** [comment] 2018-08-16 12:05
Duplicate of https://github.com/parse-community/parse-dashboard/issues/806

Please *triple* check your configurations

**Closed by flovilmart** 2018-08-16 12:05 UTC
