### ISSUE TITLE
Viewing relations on a class with a sorted column sometimes fails

### ISSUE THREAD

**Issue by cjbland** [parse-community/parse-dashboard#1630] opened 2020-12-07 00:48 UTC
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.23 of Parse Dashboard.

- [x] You're running version >=2.3.2 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

Following the instructions in the main `README.md` on my local machine is all I did.

#### Steps to reproduce

  1. Follow `Local Installation` instructions on the main `README.md`
  2. Click "Role" under "Browser"
  3. Add a role
  4. Click the "name" column to sort by name
  5. Click the "View relation" in the "users" column
  6. The page fails to load

It looks like `order: "-name"` is being sent with the query on the relation (where the order came from the main "Role" screen).

#### Logs/Trace

PostgreSQL gives the following error:

```
SELECT * FROM "_Join:users:_Role" WHERE "owningId" = 'I2GKNd41kM';
SELECT * FROM "_User" WHERE "objectId" IS NULL ORDER BY "name" ASC LIMIT 200;
ERROR:  column "name" does not exist at character 250
```

Here is some relevant data from the browser:

Request URL: https://myserver.com/parse/classes/_User
{"where":{"$relatedTo":{"object":{"__type":"Pointer","className":"_Role","objectId":"xuE91DYlpL"},"key":"users"}},"limit":200,"order":"-name","_method":"GET","_ApplicationId":"myAppId","_ClientVersion":"js2.12.0","_MasterKey":"myMasterKey","_InstallationId":"myInstallationId"}

Digging around in the local storage I found this:

```
ParseDashboard:v1:myAppId:__columnClassesSort: [{"name":"_Role","value":"-name"}]
```

This must also be applying to relations under the named class. Deleting this key and refreshing the page removes the sort on the column and I'm able to view the relation properly.

**Comment by mtrezza** [comment] 2021-11-06 14:14
I'm closing this issue as I was not able to reproduce it following the steps above with version `3.3.0-beta.2`. @cjbland If you could verify the issue still exists with the latest alpha version, please let us know and we can re-open this issue.

**Closed by mtrezza** 2021-11-06 14:14 UTC
Labels: type:bug, state:needs-investigation
