### ISSUE TITLE
Location of "edit box" doesn't adjust when columns are hidden

### ISSUE THREAD

**Issue by mrmarcsmith** [parse-community/parse-dashboard#1346] opened 2019-10-15 20:29 UTC
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.23 of Parse Dashboard.

- [x] You're running version >=2.3.2 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Deployed using the official docker image.
Client: Safari 13.0.2

#### Steps to reproduce
1. click a class "TestClass"
2. hide all fields except 1 (make sure the one showing field didn't originally have column 1)
3. double click to edit the value.
I expect the box to pop up over the value, what happens in the box pops up over the boxes "would be" location if some columns weren't hidden

Without columns hidden:
<img width="1253" alt="Screen Shot 2019-10-15 at 1 26 51 PM" src="https://user-images.githubusercontent.com/5037688/66867247-bdf64900-ef4f-11e9-917b-0b974d726cb3.png">

With columns hidden:
<img width="1249" alt="Screen Shot 2019-10-15 at 1 24 37 PM" src="https://user-images.githubusercontent.com/5037688/66866924-24c73280-ef4f-11e9-9b09-97d2f83900ec.png">

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by davimacedo** [comment] 2021-06-02 22:16
@mrmarcsmith I was looking at this issue and not able to reproduce anymore. Could you please confirm if that's still happening or not?

**Comment by mtrezza** [comment] 2021-06-03 00:13
@davimacedo I remember this issue and believe to recall that it has been fixed at some point. I am also not able to reproduce it the latest release.

**Comment by davimacedo** [comment] 2021-06-03 00:31
So let's close it for now and re-open in the case someone can reproduce.

**Closed by davimacedo** 2021-06-03 00:31 UTC
Labels: bug
