### ISSUE TITLE
Visual Bug: Misaligned row dividers

### ISSUE THREAD

**Issue by tealshift** [parse-community/parse-dashboard#566] opened 2016-10-26 03:27 UTC
<img width="677" alt="screen shot 2016-10-25 at 8 16 36 pm" src="https://cloud.githubusercontent.com/assets/7879237/19712231/f0598e5e-9af0-11e6-8a9c-ef337bbf72b8.png">

I'm using back4app which hosts version 10.0.14 of Dashboard, but I haven't seen this issue mentioned or addressed on GitHub. I have about 40 columns on this object class, and I don't know which one might be causing it.

**Comment by tealshift** [comment] 2016-10-26 03:29
Well technically the content is misaligned from the dividers... anyways, hopefully someone else has seen this or can enlighten me about the issue.

**Comment by pivanov** [comment] 2016-10-26 19:34
Can you give us more information about browser, os etc.?

**Comment by tealshift** [comment] 2016-10-27 02:52
hah I'm a fool to forget that! I'm using the latest MacOS with the latest Safari. It's been doing this since I can remember using the "beta" dashboard in Parse.com. Switching to Firefox, the bug is not present.

**Comment by tealshift** [comment] 2016-10-27 02:54
SashiDo looks pretty cool, but I already migrated. :(
Thanks for the suggestion though!

**Comment by pivanov** [comment] 2016-10-27 02:56
No problem :) if you have problems with your app just ping us :)

**Comment by steven-supersolid** [comment] 2016-10-31 12:12
Could you provide a _SCHEMA document and sample data that reproduces the issue?
Would be helpful if you can narrow it down and please check against version 1.0.19 in case it was already fixed.

Looks like it is Safari specific?

**Comment by tealshift** [comment] 2016-10-31 21:41
I'm in a bit of a time crunch now, but I can say that the visual problem occurs on rows that have a String field containing an empty string. Deleting the value resolved the problem for that row!

Setting up my app without back4app just for this seems like a hassle. I'll ask them to update their service. 'fraid I'll have to look up how to make a SCHEMA doc for you.

But honestly adding an empty string to your dashboard on 1.0.19 with Safari should be a pretty quick test.

**Comment by ssamuli** [comment] 2017-06-15 09:07
This should be fixed by #731

**Closed** 2019-01-17 19:39 UTC
Labels: wontfix
