### ISSUE TITLE
API Console 'Run as' functionality doesn't work.

### ISSUE THREAD

**Issue by aziz92** [parse-community/parse-dashboard#776] opened 2017-09-27 21:15 UTC
Using the latest dashboard/parse-server. I'm using the API console, and using the 'Run as' field. I've got the use master-key enabled. 

However, this doesn't work. I can see on the server, request.user is null. It's never set. 

Also, another weird thing is, if I turn off the master key, then in cloud code request.user IS SET. However, I can't obviously modify that user because master key is turned off and all request return with authorization error, which makes sense. 

Anyone know why or have a worked around with this?

**Comment by flovilmart** [comment] 2017-09-27 21:16
Closing as duplicate of #449

**Closed** 2017-09-27 21:18 UTC
