### ISSUE TITLE
Parse Server Customization

### ISSUE THREAD

**Issue by Supernaturalperson** [parse-community/parse-dashboard#1538] opened 2020-04-27 15:44 UTC
We need help with Parse dashboard customizations. Essentially we are looking to find a way to be able to make a new app using the Parse dashboard. If there is some guide for that?

Much appreciated Cheers

**Comment by TomWFox** [comment] 2020-04-27 18:48
Hi, this is a duplicate of [this topic](https://community.parseplatform.org/t/making-new-app-in-parse-from-dashboard/226/8) on the community forum. That was the best place to ask this type of question. We ask people to refrain from cross-posting as it can waste the time of maintainers.

**Closed by TomWFox** 2020-04-27 18:48 UTC
