### ISSUE TITLE
Cannot Scroll on Parse Dashboard /apps

### ISSUE THREAD

**Issue by yingmu52** [parse-community/parse-dashboard#1181] opened 2019-07-24 22:25 UTC
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.23 of Parse Dashboard.
my Parse Dashboard version is :`1.4.1`

- [x] You're running version >=2.3.2 of Parse Server.
my Parse Server version is: `3.3.0`

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
MacOS Mojave 10.14.5 (18F132)
node -v `v8.9.4`

#### Steps to reproduce
My dashboard has 13 apps, I am not able to scroll down. the problem goes away when I switch the dashboard version to `1.3.3`

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by davimacedo** [comment] 2019-07-24 22:58
@yingmu52 it seems that the issue is already fixed in the master branch. Can you please install from master and let me know in the case it does not work?

**Closed by davimacedo** 2019-07-24 22:58 UTC
