### ISSUE TITLE
Parse Dashboard doesn't load Push options

### ISSUE THREAD

**Issue by adammlevy** [parse-community/parse-dashboard#821] opened 2017-12-05 04:22 UTC
- [x ] You're running version >=1.0.23 of Parse Dashboard.

- [x ] You're running version >=2.3.2 of Parse Server.

- [ x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Running Parse Dashboard on Heroku 

#### Steps to reproduce
Launch dashboard
Tap 'Push'
Loading indicator freezes

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by adammlevy** [comment] 2017-12-05 04:26
This is all I see when I tap Push:
<img width="805" alt="screen shot 2017-12-04 at 8 25 04 pm" src="https://user-images.githubusercontent.com/599680/33590013-5638e4c0-d931-11e7-80ba-a25594c5b296.png">

**Comment by montymxb** [comment] 2017-12-05 05:12
Closing as this is a duplicate of #811, please see there for details regarding this, including a fix. The underlying issue has been addressed and will be in the next release.

**Closed by montymxb** 2017-12-05 05:12 UTC
