### ISSUE TITLE
Filter applied to collection also applies to viewed relation

### ISSUE THREAD

**Issue by TylerBrock** [parse-community/parse-dashboard#241] opened 2016-04-08 00:56 UTC
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!
- [N/A] You're running version >=2.1.4 of Parse Server. (Still on Parse.com)
- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.
#### Environment Setup

Linux
#### Steps to reproduce

So this isn't super important but I wanted to document the bug in case someone has time to work on it before I get to try and see if I can figure it out.
- View a collection that has a relation in the data browser (like Role).
- Filter the collection with some criteria (ex: name starts with "cool")
- Click on "View relation" field in a visible row
- See "No data to display" when viewing the relation because the filter applied to the collection is still (mistakenly) being applied to the relation.

This makes it really difficult to deal with large numbers of Roles or other collections that have relations.

Example of where this hurts (we have ~10k roles): Try to see which users are in a particular role. To find said Role one must scroll until they find it, because if leveraging filter you won't be able to view the roles in the relation.
#### Logs/Trace

Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by douglasmuraoka** [comment] 2019-08-21 13:54
Followed all steps and couldn't reproduce this bug, closing this issue.

**Closed by douglasmuraoka** 2019-08-21 13:54 UTC
Labels: bug
