### ISSUE TITLE
When some columns are invisible I can not edit visible column values

### ISSUE THREAD

**Issue by suathh** [parse-community/parse-dashboard#1362] opened 2019-10-31 07:53 UTC
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ X] You're running version >=1.0.23 of Parse Dashboard.

- [ X] You're running version >=2.3.2 of Parse Server.

- [ X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
"dependencies": {
    "csv": "^5.1.2",
    "csvtojson": "^2.0.10",
    "express": "~4.11.x",
    "kerberos": "~0.0.x",
    "parse": "~1.8.0",
    "parse-server": "*"
  },
  "scripts": {
    "start": "node index.js"
  },
  "engines": {
    "node": ">=4.3"
  }

#### Steps to reproduce
Use Manage Columns and hide any column and try to change value of any visible column

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by Simone-cogno** [comment] 2019-11-20 18:01
Any plan to fix this? The function of hiding columns is very useful but cannot be used anymore (you should disabled all the hided columns to be able to modify the fields)

**Comment by davimacedo** [comment] 2021-06-02 22:21
@suathh I was looking at this issue and not able to reproduce anymore. Could you please confirm if that's still happening or not?

**Comment by suathh** [comment] 2021-06-04 11:27
@davimacedo I tried with couple of different instances and I can say that problem is not persist anymore

**Comment by mtrezza** [comment] 2021-06-04 12:55
@suathh thanks for reporting back, closing this issue.

**Closed by mtrezza** 2021-06-04 12:55 UTC
Labels: bug
