### ISSUE TITLE
Logout button not working? 

### ISSUE THREAD

**Issue by rameshkec85** [parse-community/parse-dashboard#1198] opened 2019-08-02 10:03 UTC
I have run parse dashboard locally provided on the instructions in Readme page. I have added configuration file with app and users information. Now i am able to see login page. But when i clicked on Logout button, it not redirecting to login page (still it is on dashboard page.). 

Do we need to configure it anywhere in the code ?

**Comment by davimacedo** [comment] 2019-08-02 18:51
Can you please confirm the version that you are running?

**Comment by mtrezza** [comment] 2021-10-04 12:52
Closing because I'm not able to reproduce this with the latest version of Parse Dashboard.

**Closed by mtrezza** 2021-10-04 12:52 UTC
Labels: type:bug, state:needs-investigation
