### ISSUE TITLE
Version 1.2.0 is missing on docker hub

### ISSUE THREAD

**Issue by chrbayer** [parse-community/parse-dashboard#967] opened 2019-01-28 16:16 UTC
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.23 of Parse Dashboard.

- [X] You're running version >=2.3.2 of Parse Server.

- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Docker setup

#### Steps to reproduce
No tag for 1.2.0 on docker hub

**Comment by TomWFox** [comment] 2019-04-28 23:32
Weird, v1.3.0 is available on Docker Hub (latest version atm). I’m guessing it was due to how v1.2.0 was released on GitHub 🤷‍♂️

**Comment by TomWFox** [comment] 2019-04-28 23:37
#843 which was the release PR for v1.2.0 didn’t update the package.lock file - probably the cause.

**Comment by dplewis** [comment] 2019-06-07 02:05
Closing via https://github.com/parse-community/parse-dashboard/pull/1100

**Closed by dplewis** 2019-06-07 02:05 UTC
Labels: help wanted, needs investigation
