### ISSUE TITLE
Parse Dashboard requires active internet connection

### ISSUE THREAD

**Issue by Codzaa** [parse-community/parse-dashboard#2009] opened 2022-01-22 08:47 UTC
After a fresh installation of Parse Dashboard it wont run if Im not connected to the internet.
I am in a place where I do not have access to internet , and I am trying to work offline.
Everytime I connect to the internet it works just fine, but when I dont have have internet,,,nothing

### Here is the Command I am using

parse-dashboard --appId yourAppId --masterKey yourMasterKey --serverURL "https://localhost:1337/parse" --appName myapp

**Comment by mtrezza** [comment] 2022-01-22 11:20
> I am in a place where I do not have access to internet , and I am trying to work offline

Could you describe how you intend to "work offline" with Parse Dashboard? Using the issue template as required could help others better understand your request.

**Comment by Codzaa** [comment] 2022-01-23 06:37
@mtrezza Thanks for replying.
I just simply want to run parse dashboard on my local machine without internet access.

Here is the error I'm getting if my machine is does not have internet connection

![image](https://user-images.githubusercontent.com/35093657/150667561-ca22deb6-ac81-4c85-af2f-772744c4537d.png)


After connecting to the internet it works.

![image](https://user-images.githubusercontent.com/35093657/150667702-d51cac4a-d0c8-4da3-b598-168601c80506.png)

Is there some configurations I have to edit for this to work?

**Comment by damianstasik** [comment] 2022-01-23 09:27
It is caused by the mechanism that checks if there are any updates. We could add a `catch` block that assigns an empty arrray to the `newFeaturesInLatestVersion` variable if there were any errors. This should also handle other types of errors like npm registry being unavailable due to downtime etc.

What do you think @mtrezza?

**Comment by mtrezza** [comment] 2022-01-23 11:11
I see, that's the feature that has been fixed / reactivated recently. Yes, I think this should just silently and gracefully fail if it can't retrieve any data, for whatever reason. It's more of a non-essential "marketing" feature.

**Comment by Codzaa** [comment] 2022-01-23 11:21
@visualfanatic @mtrezza  So is there a work around or some hacky stuff I can do to get to work for now?

**Comment by damianstasik** [comment] 2022-01-23 11:28
@mtrezza @Codzaa Here is PR with the change: https://github.com/parse-community/parse-dashboard/pull/2015

**Comment by mtrezza** [comment] 2022-01-23 11:44
Closing via #2015.
Released in 4.0.0-alpha.14.

**Closed as completed** 2022-01-23 11:44 UTC
Labels: type:bug
