### ISSUE TITLE
Uncaught (in promise) TypeError: e.getUTCDate is not a function

### ISSUE THREAD

**Issue by lincyim** [parse-community/parse-dashboard#2408] opened 2023-03-16 03:41 UTC
### Steps to reproduce
1. click _User collection
2. open filter
3. set condition as objectId equals 'xxxx'
4. click ok

### Actual Outcome
the whole page turns out to be blank.

### Expected Outcome
show the result after filtering.

### Environment
parse-dashboard 5.0.0
node 16.8.1
ubuntu 22

Dashboard
- Parse Dashboard version: `5.0.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `Version 111.0.5563.64 (Official Build) (x86_64)`

Server
- Parse Server version: `5.4.0`
- Operating system: `Ubuntu`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `remote`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `5.0.6`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `remote`

### Logs
Uncaught (in promise) TypeError: e.getUTCDate is not a function
    at $l (dashboard.bundle.js:2:2473544)
    at i.value (dashboard.bundle.js:2:2579615)
    at i.value (dashboard.bundle.js:2:2584905)
    at ss (dashboard.bundle.js:2:1669133)
    at vl (dashboard.bundle.js:2:1686759)
    at t.unstable_runWithPriority (dashboard.bundle.js:2:1841656)
    at Hi (dashboard.bundle.js:2:1630862)
    at ml (dashboard.bundle.js:2:1683425)
    at rl (dashboard.bundle.js:2:1679579)
    at dashboard.bundle.js:2:1631153

**Comment by AshishBarvaliya** [comment] 2023-04-13 04:10
@lincyim Not able to reproduce, could you provide more details please?

![CPT2304130006-1203x485](https://user-images.githubusercontent.com/49753983/231650606-065f81fa-225d-426f-ba2a-911d921185ee.gif)



Versions - Dashboard - 5.0.0, Server: 5.4.0

**Comment by mtrezza** [comment] 2023-06-05 21:40
I'm closing this as it was not reproducible and there were no further responses. Please follow up on any questions asked and further steps suggested in the thread and we can re-open this issue.

**Closed as completed by mtrezza** 2023-06-05 21:40 UTC
Labels: type:bug
